# Generated by Django 3.0.7 on 2020-06-20 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribers',
            options={'verbose_name': 'Susbcriber', 'verbose_name_plural': 'Subscribers'},
        ),
    ]
